export const uoms: {value: string, label: string}[] = [
    {value: 'PCS', label: 'Pieces (PCS)'},
    {value: 'BOX', label: 'Box (BOX)'},
    {value: 'PACK', label: 'Pack (PACK)'},
    {value: 'SET', label: 'Set (SET)'},
    {value: 'KG', label: 'Kilogram (KG)'},
    {value: 'GR', label: 'Gram (GR)'},
    {value: 'ML', label: 'Milliliter (ML)'},
    {value: 'L', label: 'Liter (L)'},
    {value: 'DOZ', label: 'Dozen (DOZ)'},
    {value: 'ROLL', label: 'Roll (ROLL)'},
    {value: 'PAK', label: 'Pak (PAK)'},
    {value: 'SACK', label: 'Sack (SACK)'},
    {value: 'TON', label: 'Ton (TON)'},
    {value: 'CARTON', label: 'Carton (CARTON)'},
    {value: 'CASE', label: 'Case (CASE)'},
    {value: 'BAG', label: 'Bag (BAG)'},
    {value: 'BUNDLE', label: 'Bundle (BUNDLE)'},
    {value: 'PAIL', label: 'Pail (PAIL)'},
    {value: 'TIN', label: 'Tin (TIN)'},
    {value: 'JAR', label: 'Jar (JAR)'},
    {value: 'BOTOL', label: 'Botol (BOTOL)'},
    {value: 'KG/B', label: 'Kilogram per Box (KG/B)'},
    {value: 'KG/P', label: 'Kilogram per Pack (KG/P)'},
    {value: 'L/B', label: 'Liter per Box (L/B)'},
    {value: 'L/P', label: 'Liter per Pack (L/P)'},
];

